samsarahq/taskrunner

cache/cache.go
cache/git.go
clireporter/cli.go
executor.go
goextensions/builder.go
registry.go
runner.go

Tasks will now be able to be registered like this:
```go
var genGQL = taskrunner.Add(&taskrunner.Task{
// ...
})
taskrunner.Group(
"gen",
genGQL, // ...
)
```
and `Run` will just take run options:
```go
taskrunner.Run(...opts)
```

Add Task Registry for registering and grouping tasks

---

executor.go
runner.go

This PR fixes an issue where errors for unknown tasks are not propagated in watch mode.
example output:
```
$taskrunner
2019/03/05 13:08:08 Using config /project/user.taskrunner.json
2019/03/05 13:08:08 Desired tasks: whatever
2019/03/05 13:08:08 Watch mode: true
2019/03/05 13:08:08 run error:
undefined task name
github.com/samsarahq/taskrunner.(*Executor).Run: task whatever is not defined
```

taskrunner: propagate well-known undefined task name error

---

watcher/watcher.go

Came across this while moving canary. Makes sense to keep this file up to date

watcher/watcher.go: updating node modules

---

runner.go
task.go

example output: 
```
$ taskrunner -describe
...
mytask
mytask/build	 Generates client bundle. Compiles typescript.
```
I tested this by adding a `Description` field to a task called `mytask/build`
I added a -describe option instead of modifying -list because I wanted to maintain fzf (fuzzy find) compatibility. I tried running taskrunner commands with fzf using -describe instead of -list. No matter what punctuation I wrapped the Description with, taskrunner always tried to run every word in the description as a task. I tried # and quotes and semi-colons.

Add a Description field for more detailed documentation of tasks

---

watcher/watcher.go

There was a typo in the eventFlag map, the actual events are called `MOVED_TO` and `MOVED_FROM`. This was causing taskrunner to silently kill the watcher goroutine when either of these events came through
I also changed the ignore hack to be generalized to all of the `node_modules` folders; `--exclude` does a regex match
Considerations:
* we might want to also ignore `copied-ts` folders for driver app and Troy
* we might want to also ignore `.git/index.lock`

watcher: fix event names for linux

---

config.go

Summary: If your main directory resolves from a symbolic link,
then you won't get taskrunner invalidation from fswatch (it requires
non-symbolic links).  This commit changes the "WorkingDir" to resolve
symbolic links to get a "true" absolute directory.
We found this after scratching our heads a while trying to figure out
why we couldn't get invalidations to work.
Test Plan: cd'ed to a symbolic link firmware directory, tested that
taskrunner invalidations didn't work before this change, and that they
did work after the change.

go config: Resolve symbolic links for fswatch

---

clireporter/linebufferedwriter.go
clireporter/prefixedwriter.go

Some tools, like jest, output non-buffered text, which causes
taskrunner to split the output across multiple lines non-deterministically.
This change effectively does the same thing as https://github.com/samsara-dev/backend/pull/46555, except it does it internal to taskrunner rather than as part of the task itself.
Only one of these 2 PRs needs to merge for the output to be fixed.
I don't have a strong preference for which one we pick; the other PR is unable to have side effects in other tasks though

clireporter: buffer output by line

---

executor.go

We noticed an issue with short-lived KeepAlive tasks where the invalidation
plan would be attempted after shutdown had already started. To prevent that from
panicking during shutdown (we'd try to publish events on a closed event channel),
we check context cancellation here before running any invalidation.
In general, the concurrency story in the executor feels pretty fragile - we may consider
re-examining this code in more detail later. I want to ship this change as a stop-gap
in the meantime.

executor: check context cancellation before invalidation

---

executor.go
task_execution.go
task_handler.go

Canceled is different from done because canceled did not succeed and should not try to kick off further tasks. Previously, canceled tasks would get stuck in running state even though they stopped.

executor: add canceled state

---

goextensions/builder.go

This change replaces the use of the `GOROOT` environment variable with the more robust `runtime.GOROOT()` method from the stdlib.
This is because Taskrunner will currently fail to find packages from the stdlib if GOROOT is not explicitly defined in an environment variable when using Go Modules.

builder: use runtime pkg to resolve GOROOT

---

runner.go

noticed the `--describe` output is kinda messy and could benefit from tabwriter's consistent spacing
tested this manually with the screenshots below.
before:
after:

runner: use tabwriter to format --describe

---

runner.go
task.go

This will allow us to set a task to Hidden. To start, this will indicate
if a task will be shown in -list or -listall in taskrunner.
This will help avoid devs from using tasks that aren't meant to be
called. For example, in taskrunner devbox/run there are multiple
commands that we want to run in parallel, but could easily be confused
for devbox/run. While if devs truly want to they will still be able to
see all the tasks via -listall.
In the future, this could be used for ordering within the TUI.
I updated my vendor locally, I ran -list and then changed the /buid tasks, then set `Hidden` to true and then reran -list
```
❯ taskrunner -list | rg build | wc -l
515
❯ taskrunner -list | rg build | wc -l
27
❯ taskrunner -listall | rg build | wc -l
515
```

task,runner: allow tasks to be marked as Hidden

---

README.md

This pull request adds very simple documentation to the readme of taskrunner to allow anyone to get started. This is not the most optimal way of using the taskrunner but the quickest and easiest to setup.
Closes #4

[Hacksara 2021] Add Simple Documentation to Taskrunner

---

runner.go
runner_internal_test.go

https://samsaradev.atlassian.net/browse/CICD-630
This change fixes a bug where passing an invalid task name as the first argument would not trigger an error (e.g. `taskrunner invalidtask`).
The reason why this was not happening is b/c we were validating whether the args passed to taskrunner and silently leaving them out of the map of desired tasks/flags if they were invalid.
This was especially apparent for invalid task names passed as the first arg since invalid task names passed after a valid task name were treated as flags (and would error as an invalid flag).
Validation happens within the executor, so let's keep that pattern and pass invalid task names as part of the desired tasks we pass into the executor and let validation happen there.
_Before (would just run "taskrunner" as if no …

taskrunner runner: include invalid task names in desired task set

---

runner.go
runner_internal_test.go

Initially, we solely relied on the executor to validate tasks passed through the CLI as args.
Unfortunately, this makes it difficult to distinguish between whether an arg is an argument to a flag being passed into taskrunner directly (since we allow flag vals to be passed after a space).
To ensure we do not accidentally pass invalid tasks that are meant to be args to taskrunner flags, validate tasks when grouping tasks and flags from the CLI args together.

taskrunner runner: add task validation when grouping tasks/flags

---

logger.go

If LoggerFromContext returns nil, then the log is dropped.
Instead of dropping the log, print a warning and fallback to using `fmt.Printf` to ensure:
* The log is still shown
* The developer is warned that no logger was found

taskrunner logger: if no logger found in ctx, fallback to Printf

---

runner.go

Since we have released flag support, we now support:
`taskrunner [task] --help` which gives rich details on the task like
description, supported flags.
looks like
```
[Usage]
taskrunner [task...]
taskrunner [task] --help
taskrunner [option]
[Options]
-config string
Configuration file to use
-describe
Describe all tasks
-ignore-cache
Ignore task invalidation cache
-list
List all tasks except those marked "Hidden"
-listAll
List all tasks including those marked as "Hidden"
-non-interactive
Non-interactive mode (only applies when running the default set of tasks)
-watch
Run in watch mode (only applies when passing custom tasks)
[Example Usage]
`taskrunner mytask`
`taskrunner mytask ---help`
`taskrunner mytask1 mytask2`
`taskrunner mytask --mode=dev`
`taskrunner --config ./customconfig.json …
```

runner: add task specific help command to --help

---

.github/workflows/main.yml

This configures the use of `taskrunner`'s `go.mod` to dynamically determine the proper Go version to use in CI from a single source of truth, rather than redundantly hard-coding that value within the workflow YAML.

GH Actions CI: determine Go version from go.mod

---

process.go

`onInterruptSignal` is a function that accepts a cleanup function and
runs it on SIGINT and SIGTERM. Update to also run cleanup on SIGHUP.
Major use case is to handle broken SSH connections.
Tested using VSCode remote terminal and manual SSH over iTerm.

process: also handle SIGHUP in `onInterruptSignal`

---

.github/workflows/main.yml

actions/cache@v2 is deprecated, so we should update to the latest version. Any actions using v2 will instantly fail, so this is necessary to get our actions CI working.
Version 4 is backwards compatible. 
Notes here: https://github.com/actions/toolkit/tree/main/packages/cache

gh workflows: update actions/cache version

---

task.go

Add Owner field to Task struct.

task: add Owner field

---

buildkitereporter/buildkitereporter.go

Now that we have added optional owners to Taskrunner tasks, in the event a task fails in a Buildkite workflow, this will include the owner in the resulting annotation.
Example:
Above task has an owner, task below does not
Update to put owner below summary:

buildkitereporter: add owner to annotations
